apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJlRzlzYjNCdmF6cG5hSEJmYzJ4NU9HVm5lbkl6ZUdGSlJuYzRSM2xHYldKbWJuQmtaM1UzVFhjNE1GQnBORmRWIn19fQ==
type: kubernetes.io/dockerconfigjson
